# Site settings
title: Rushiera
description: A blog about Rushiera
#baseurl: "/particle"	"/myblog"
url: https://rushiera.github.io/

#at call  {{ site.name }}
username: Rushiera
user_title: I just want to keep on just wait and see
twitter: undefined
email: undefined
github: undefined
tencent:  undefined
google:  undefined


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
